- name: User setup (home)
  hosts: localhost
  connection: local
  gather_facts: true
  become: false

  vars:
    user_home: "{{ ansible_env.HOME }}"
    user_bin: "{{ ansible_env.HOME }}/.local/bin"

  pre_tasks:
    - name: Ensure XDG dirs
      file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - "{{ user_bin }}"
        - "{{ user_home }}/.local/share"
        - "{{ user_home }}/.config"
        - "{{ user_home }}/.cache"

  roles:
    - role: tools/source_code_pro
      tags: [source-code-pro]

    - role: tools/greenclip
      tags: [greenclip]

    - role: tools/zoxide
      tags: [zoxide]

    - role: tools/fzf
      tags: [fzf]

    - role: tools/typst
      tags: [typst]

    - role: tools/grb
      tags: [grb]

      #    - role: infra/systemd_user_timer
      #      tags: [timers]

    - role: tools/texlive_tlmgr
      tags: [texlive, tlmgr]

    - role: tools/wakatime_cli
      tags: [wakatime, wakatime-cli]

    - role: tools/rust
      tags: [rust]

    - role: tools/rbw
      tags: [rbw, bitwarden, password-manager]



    - role: tools/gdu
      tags: [gdu, disk-usage, analyzer]

    - role: tools/github_script
      vars:
        github_script_config: "translate-shell"
      tags: [github-script, translate-shell, translator]
