---
- name: Ensure vifm config directory exists
  file:
    path: "{{ ansible_env.HOME }}/.config/vifm"
    state: directory
    mode: '0755'

- name: Clone vifm_devicons repository
  git:
    repo: "https://github.com/thimc/vifm_devicons.git"
    dest: "{{ ansible_env.HOME }}/.local/src/vifm_devicons"
    update: true
    force: true

- name: Check if vifmrc exists
  stat:
    path: "{{ ansible_env.HOME }}/.config/vifm/vifmrc"
  register: vifmrc_exists

- name: Create vifmrc if it doesn't exist
  file:
    path: "{{ ansible_env.HOME }}/.config/vifm/vifmrc"
    state: touch
    mode: '0644'
  when: not vifmrc_exists.stat.exists

- name: Add devicons source to vifmrc
  lineinfile:
    path: "{{ ansible_env.HOME }}/.config/vifm/vifmrc"
    line: "source {{ ansible_env.HOME }}/.local/src/vifm_devicons/favicons.vifm"
    state: present

- name: Verify favicons.vifm file exists
  stat:
    path: "{{ ansible_env.HOME }}/.local/src/vifm_devicons/favicons.vifm"
  register: favicons_file
  failed_when: not favicons_file.stat.exists