---
galaxy_info:
  author: System Administrator
  description: Build and install nvim-qt (Qt GUI for Neovim) from source using existing Neovim installation
  license: license (GPL-2.0-or-later, MIT, etc)
  min_ansible_version: "2.10"
  
  platforms:
    - name: Ubuntu
      versions:
        - "20.04"
        - "22.04"
        - "24.04"
    - name: Debian
      versions:
        - buster
        - bullseye
        - bookworm

  galaxy_tags:
    - neovim
    - nvim-qt
    - qt
    - gui
    - editor
    - development
    - build

dependencies: []
