---
galaxy_info:
  author: ansible-playbooks
  description: Install and configure Spacemacs
  license: MIT
  min_ansible_version: 2.9
  
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - bullseye
        - bookworm

  galaxy_tags:
    - development
    - editor
    - emacs
    - spacemacs

dependencies: []