- name: Ensure keyring directory exists
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Download Google Linux signing key
  get_url:
    url: https://dl.google.com/linux/linux_signing_key.pub
    dest: /etc/apt/keyrings/google-linux-signing-key.pub
    mode: "0644"

- name: Convert key to GPG (dearmor)
  command: gpg --dearmor --yes --output /etc/apt/keyrings/google-linux-signing-key.gpg /etc/apt/keyrings/google-linux-signing-key.pub
  args:
    creates: /etc/apt/keyrings/google-linux-signing-key.gpg

- name: Add Google Chrome apt repository
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/google-linux-signing-key.gpg] https://dl.google.com/linux/chrome/deb/ stable main"
    state: present
    filename: google-chrome

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Google Chrome
  apt:
    name: google-chrome-stable
    state: present
